version: '3'

services:
  nginx:
    image: pppy/s3-nginx-proxy
    build: .
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8125:8125
    volumes:
      - ./data/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./data/etc/proxy-config:/etc/proxy-config
      - ./data/docker-entrypoint.d:/docker-entrypoint.d
  config:
    image: pppy/s3-nginx-proxy
    build: .
    command: /srv/config.sh
    volumes:
      - ./data/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./data/etc/proxy-config:/etc/proxy-config
      - ./data/docker-entrypoint.d:/docker-entrypoint.d
